server:
  port: 9090

mybatis:
  type-aliases-package: cn.iamcrawler.crawlertest.entity
  mapper-locations: cn.iamcrawler.crawlertest.mapper.*.xml
  global-config:
    refresh-mapper: true
#liquibase:
#  change-log: classpath:liquibase/master.xml

spring:
  datasource:
    url: jdbc:mysql://www.iamcrawler.cn:8066/mycatDatabase?serverTimezone=Asia/Shanghai
    username: crawler
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
